config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'product#index'
  resources :search, only: [:index]
  resources :product do
    resources :order_product, only: %i[new create]
    resources :product_cart, only: %i[new create]
    resources :comments
  end

  resources :cart
  devise_for :users
  resources :order
  resources :order_product, only: %i[index show]
  resources :product_cart, only: %i[show destroy index edit update] do
    resource :checkout, only: [:create]
  end
  resources :webhooks, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :product_carts, dependent: :destroy
  has_many :products, through: :product_carts, dependent: :destroy
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :body, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true  
  
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :product_carts
  has_many :carts, through: :product_carts, dependent: :destroy

  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products, dependent: :destroy

  validates :name, :price, :description, presence: true
  has_many_attached :images
  validate :check_image_type

  def check_image_type
    images.each do |image|
      errors.add(:image, 'must be a JPEG or PNG') unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
    end
  end
end

app/models/product_cart.rb
# frozen_string_literal: true

class ProductCart < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  validates :quantity, presence: true
  validates :product_id, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :name, presence: true

  has_one_attached :profile_image
  validate :check_image_type

  def check_image_type
    if profile_image.attached? && !profile_image.content_type.in?(%w[image/jpeg image/png image/jpg])
      errors.add(:profile_image, 'must be a JPEG or PNG')
    end
  end

  def profile_image_thumbnail
    if profile_image.attached? && profile_image.content_type.in?(%w[image/jpeg image/png image/jpg])
      profile_image.variant(resize: '60x60!').processed
    else
      '/default_profile.jpg'
    end
  end

  def to_s
    email
  end

  after_create do
    customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: customer.id)
    @cart = Cart.create(user_id: id)
  end
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/order_controller.rb
# frozen_string_literal: true

class OrderController < ApplicationController
  def index; end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(user_id: current_user.id)
    if @order.save
      redirect_to order_index_path, notice: 'order was successfully created.'
    else
      redirect_to root, notice: 'Order was failed.'
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:user_id).with_defaults(user_id: current_user.id)
  end
end

app/controllers/product_controller.rb
# frozen_string_literal: true

class ProductController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :find_product, only: %i[show edit destroy update]

  def index
    @query = Product.ransack(params[:q])
    @products = @query.result
  end

  def new
    @product = current_user.products.build
  end

  def show
    @comment = Comment.new
    @product_cart = ProductCart.new
    @comments = @product.comments
  end

  def create
    @product = current_user.products.build(param_for_product)
    if @product.save
      redirect_to product_index_path
    else
      render 'new'
    end
  end

  def edit
    authorize @product
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to :root
  end

  def update
    authorize @product
    if @product.update(param_for_product)
      redirect_to :root
    else
      render 'new'
    end
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def param_for_product
    params.require(:product).permit(:name, :description, :price, images: [])
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cart_helper.rb
# frozen_string_literal: true

module CartHelper
end

app/helpers/checkouts_helper.rb
# frozen_string_literal: true

module CheckoutsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/order_helper.rb
# frozen_string_literal: true

module OrderHelper
end

app/helpers/order_product_helper.rb
# frozen_string_literal: true

module OrderProductHelper
end

app/helpers/product_cart_helper.rb
# frozen_string_literal: true

module ProductCartHelper
end

app/helpers/product_helper.rb
# frozen_string_literal: true

module ProductHelper
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/helpers/subscription_helper.rb
# frozen_string_literal: true

module SubscriptionHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/product/_details.html.erb
<div class=card-img-top> 
 <% (0..product.images.count).each do |image|%>
<%= image_tag(product.images[image])%>
 <%end%> 
 </div>
 <br>
<h5 class="card-title">Name:<%= product.name%></h5>  <br>
  <p class="card-text"><strong>Description: </strong><%= product.description%></p>

 <p class="card-text"><strong>Price:</strong><%= product.price%>Rs-/</p>

app/views/product/_form.html.erb
<%= form_for @product,url: url do |f|%>
<div class='card  p-3 mb-5'>
<div>Name: <%= f.text_field :name,:class => 'form-control'%></div><br><br>
<div>Product Picture: <%=f.file_field :images,multiple: true,:class => 'form-control'%></div><br><br>
<div>Description: <%= f.text_field :description,:class => 'form-control'%></div><br><br>
<div>Price: <%= f.text_field :price,:class => 'form-control'%></div><br><br>
<%=submit_tag%>
</div>
<%end%>

app/views/product/_search.html.erb
 <%=search_form_for(@query,url:product_index_path,method: :get ) do |form|%>
   <div class='d-flex justify-content-center'> <%=form.search_field :name_i_cont_any, :class=> 'form-control mr-sm-2',placeholder:" Search product"%>
    <%=form.submit "Submit",:class => 'btn btn-outline-success my-2 my-sm-0'%></div>
    <%end%>  

app/views/product/edit.html.erb
<div class="container">
<h1 class="card-title">Edit Product</h1>
<%=render partial: 'form' ,:locals => {url: product_path }%>
</div>

app/views/product/index.html.erb
<br>
<div class"search_bar"><%=render 'search' %></div>
  <div class="container">
    <div class="row"> 
        <h1> All Products</h1>
        <% if user_signed_in?%>
        <div><%=link_to "Add Product",new_product_path(@product),:class => "btn btn-lg btn-secondary"%></div><br><br>
        <%end%>
      <% @products.each do |product|%>
       <div class="col-md-4">
        <div class="card shadow-lg p-3 mb-5 bg-white rounded" >
         <div class="card-body">
         <%=render 'details' ,product: product%>
          <div><%= link_to "View Product",product_path(product), :class => "btn btn-secondary"%>&nbsp&nbsp&nbsp</div>
          </div>
        </div>
        </div>
        <%end%>     
    </div>
  </div>

app/views/product/new.html.erb
<div class="container">
<h1 class="card-title">Adding a Product</h1>
<%if @product.errors.any?%>
  <h2>Errors: </h2>
  <% @product.errors.full_messages.each do |message| %>
    <li><%= message%></li>
  <%end%>
  <br><br>
<%end%>
<%=render partial: 'form' ,:locals => {url: product_index_path }%>
</div>

app/views/product/show.html.erb
<article class="container"><br><br>
  
  <%=render 'details',product: @product%>

<div class='d-flex justify-content-flex-start'>
  <%if user_signed_in?%>
    <% if @product.user_id == current_user.id%>
        <div>  <%=link_to "Edit Product",edit_product_path(@product),:class => "btn btn-secondary"%></div>
        <div>  <%=link_to "Delete Product",product_path(@product),method: :delete,:class => "btn btn-secondary"%></div>
     <%end%>
  <%end%> 
   <div>  <%= link_to "Add to cart",product_product_cart_index_path(@product),method: :create,:class => "btn btn-secondary"%></div>
</div>
<br>
  
<%if user_signed_in?%>
  <%= form_with model: [@product,@comment] do |f|%>
   <%= f.text_field :body%>
   <%=f.submit%>
   <%end%>

  <%else%>
<p> you need to <%= link_to 'log in',new_user_session_path%> before you can comment on product.</p>
<%end%>

<h2>Comments:</h2><br>

<div id="comment_section">
<%@comments.each do |comment|%>

<%=render 'comments/comment',comment:comment%>
<%end%>

</div>
</article>