config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'product#index'
  resources :search, only: [:index]
  resources :product do
    resources :order_product, only: %i[new create]
    resources :product_cart, only: %i[new create]
    resources :comments
  end

  resources :cart
  devise_for :users
  resources :order
  resources :order_product, only: %i[index show]
  resources :product_cart, only: %i[show destroy index edit update] do
    resource :checkout, only: [:create]
  end
  resources :webhooks, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :product_carts, dependent: :destroy
  has_many :products, through: :product_carts, dependent: :destroy
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :body, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true  
  
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :product_carts
  has_many :carts, through: :product_carts, dependent: :destroy

  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products, dependent: :destroy

  validates :name, :price, :description, presence: true
  has_many_attached :images
  validate :check_image_type

  def check_image_type
    images.each do |image|
      errors.add(:image, 'must be a JPEG or PNG') unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
    end
  end
end

app/models/product_cart.rb
# frozen_string_literal: true

class ProductCart < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  validates :quantity, presence: true
  validates :product_id, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :name, presence: true

  has_one_attached :profile_image
  validate :check_image_type

  def check_image_type
    if profile_image.attached? && !profile_image.content_type.in?(%w[image/jpeg image/png image/jpg])
      errors.add(:profile_image, 'must be a JPEG or PNG')
    end
  end

  def profile_image_thumbnail
    if profile_image.attached? && profile_image.content_type.in?(%w[image/jpeg image/png image/jpg])
      profile_image.variant(resize: '60x60!').processed
    else
      '/default_profile.jpg'
    end
  end

  def to_s
    email
  end

  after_create do
    customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: customer.id)
    @cart = Cart.create(user_id: id)
  end
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cart_helper.rb
# frozen_string_literal: true

module CartHelper
end

app/helpers/checkouts_helper.rb
# frozen_string_literal: true

module CheckoutsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/order_helper.rb
# frozen_string_literal: true

module OrderHelper
end

app/helpers/product_cart_helper.rb
# frozen_string_literal: true

module ProductCartHelper
end

app/helpers/product_helper.rb
# frozen_string_literal: true

module ProductHelper
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/helpers/subscription_helper.rb
# frozen_string_literal: true

module SubscriptionHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>EcommerenceProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<script src="https://js.stripe.com/v3/"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
  <%if notice%>
   <p class="notice"><%= notice %></p>
  <%end%>
   <%if alert%>
    <p class="alert"><%= alert %></p>
  <%end%>
   
    <div class="topnav"> 
    <%= link_to 'Home' ,root_path %>
    <%= link_to 'My Cart' ,product_cart_index_path%>
    <%= link_to 'My Orders' ,order_product_index_path %>
    <% if user_signed_in?%>    
      <%= link_to 'Sign out' ,destroy_user_session_path ,method: :delete %>
     <%=image_tag(current_user.profile_image_thumbnail) %>
    <%else%>
      <%= link_to 'Sign in' ,user_session_path %>
      <%= link_to 'Sign up' , new_user_registration_path %>
    <%end%>

   
    </div>
 
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    
  </body>
</html>